### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by x676f64** [tien/dot-console#129]
Hi, I really like the extrinsic builder, a couple feature suggestions if you are so inclined:

- Ability to duplicate a call/set of calls with or without copying the data (maybe two different buttons)
- Ability to pass the encoded call data as a GET parameter/produce a copyable deep-link that populates the extrinsic builder with your call data similar to pjs.org
- Alphabetically sort the extrinsic pallet and method lists

Thanks

**Comment by tien** [comment]
Thanks for the great suggestions! I've just pushed some quick changes for those features, let me know if it's what you have in mind 🙏

**Comment by x676f64** [comment]
Awesome, this is such a time saver! can you also sort this column please?

![image](https://github.com/user-attachments/assets/dcb007e2-ec68-4002-88d0-3c51c8decc47)

Basically any nested drop-down should be alpha sorted please 
![image](https://github.com/user-attachments/assets/3faad17a-0c5b-4af0-af02-cb2cb9c3a007)

**Comment by tien** [comment]
Oops forgot about that one, just pushed an update 🙏
