### ISSUE TITLE
BUG - Inadvertent value changes due to scrolling

### ISSUE THREAD

**Issue by x676f64** [tien/dot-console#136]
If a integer value based input box is focused and my mouse pointer is positioned over the input box while I use my scroll wheel it will change the value.

![image](https://github.com/user-attachments/assets/be63dbf9-b926-4607-8545-afcdf0ed5c46)
(sorry mouse pointer is not captured in screenshot)

Note the arrows indicating the ability to change values incrementally.

Ideally this should be a regular input box.

Thanks for the support!

**Comment by tien** [comment]
Doesn't happen with scrolling on a trackpad, will test & resolve sometime next week when I can find my mouse again :p

**Comment by x676f64** [comment]
> Doesn't happen with scrolling on a trackpad, will test & resolve sometime next week when I can find my mouse again :p

haha yeah, you do need a scroll wheel to simulate it I think but you should be able to tell if the field is incorrect or not based on this 
![image](https://github.com/user-attachments/assets/4ffe85ae-42dc-4899-87b5-7cd76dafbf39)
If those arrows are there and it's a value field, that's an issue
